server: 18.135.98.179
server_user: algo
ansible_ssh_port: "4160"
ansible_ssh_private_key_file: configs/algo.pem
algo_provider: lightsail
algo_server_name: SATech-VPN
algo_ondemand_cellular: True
algo_ondemand_wifi: True
algo_ondemand_wifi_exclude: X251bGw=
algo_dns_adblocking: True
algo_ssh_tunneling: False
algo_store_pki: True
IP_subject_alt_name: 18.135.98.179
ipsec_enabled: True
wireguard_enabled: True
